export const SELECT_COLUMNS_LISTINGS = `
        id,
        title,
        description,
        type_of_listing,
        status_code,
        shipment_code,
        departure_date,
        max_weight_kg,
        price_per_unit,
        currency_code,
        photos,
        is_verified,
        created_at,
        type_of_listing,
        owner:profiles!listings_owner_id_profiles_id_fk(
          id,
          full_name,
          bucket_avatar_url
        ),
        origin:airports!listings_origin_id_airports_id_fk(
          id,
          city,
          name,
          iata_code
        ),
        destination:airports!listings_destination_id_airports_id_fk(
          id,
          city,
          name,
          iata_code
        )
      `;